'use strict';

/**
 * docs/SCREENS.md generator.
 *
 * Reads docs/screens/captions.tsv (filename<TAB>caption, written during the browser
 * walkthrough) and every PNG in docs/screens/, and writes docs/SCREENS.md grouped by the
 * walkthrough section encoded in the 3-digit filename prefix. Fails if a PNG has no caption
 * or a caption has no PNG, so the document can never drift from the screenshot set.
 *
 *   node tools/screens.js          regenerate docs/SCREENS.md
 *   node tools/screens.js --check  exit 1 if docs/SCREENS.md on disk is stale
 */

const fs = require('node:fs');
const path = require('node:path');

const SCREENS_DIR = path.join('docs', 'screens');
const CAPTIONS_FILE = path.join(SCREENS_DIR, 'captions.tsv');
const OUTPUT_FILE = path.join('docs', 'SCREENS.md');

const SECTIONS = [
  { from: 1, to: 2, title: 'Login (names.nsf) and Heraldry home (HeraldryHome.xsp)', blurb: 'EAMS-A / SAML stub with passwordless synthetic persona table and `DomAuthSessId` session cookie; landing page for unit supply / S4 requesters, vendors and TACOM staff.' },
  { from: 3, to: 26, title: 'Heraldry workflows: DD Form 1348-6 request, modify, cancel, release, status inquiry, SES flag, vendor queue', blurb: 'Every action is enforced server-side by the @Formula port; released requests return the legacy `Error 4091` block.' },
  { from: 27, to: 41, title: 'Heraldry Domino views and documents (?OpenView / ?OpenDocument / $File)', blurb: 'Categorized `<table border=1>` views with twisties, collapse/expand, category filters and `$File` attachment metadata.' },
  { from: 42, to: 50, title: 'Veteran medals Domino views (vetmedals.nsf)', blurb: 'Stage, authorization-date, aging, engraving, assembly, warehouse, ship-confirm and CSR lookup views.' },
  { from: 51, to: 60, title: 'Awards case lifecycle (CaseView.xsp)', blurb: 'Authorized -> Engraving -> Assembly/QC -> Warehouse -> Shipped -> Closed, plus case notes, hold/release and role gating.' },
  { from: 61, to: 67, title: 'Engraving queue and CSR lookup XPages', blurb: 'Engraving job lifecycle with proof check; CSR lookup by case number, surname, SSN last-4 / service number digits.' },
  { from: 68, to: 72, title: 'Design inventory (/design)', blurb: 'Discovery screen: forms, views, agents, XPages with field/column/LoC counts and design source.' },
  { from: 73, to: 77, title: 'Agents menu (/agents): NightlyAging and ImportAuthorizationFile', blurb: 'Manual runs of the scheduled agents, including multipart upload of an HRC/NPRC authorization file.' },
  { from: 78, to: 999, title: 'Audit log, error page and wide-table layout', blurb: 'JSON audit trail rendered at /audit, generic Domino-style error page, horizontal scrolling of wide design/audit tables inside the content cell.' },
];

function readCaptions() {
  const lines = fs.readFileSync(CAPTIONS_FILE, 'utf8').split(/\r?\n/).filter((l) => l.trim());
  const out = new Map();
  for (const line of lines.slice(1)) {
    const [file, ...rest] = line.split('\t');
    out.set(file.trim(), rest.join('\t').trim());
  }
  return out;
}

function build() {
  const captions = readCaptions();
  const pngs = fs.readdirSync(SCREENS_DIR).filter((f) => f.endsWith('.png')).sort();
  const missingCaption = pngs.filter((f) => !captions.has(f));
  const missingFile = [...captions.keys()].filter((f) => !pngs.includes(f));
  if (missingCaption.length || missingFile.length) {
    throw new Error(`captions.tsv out of sync: no caption for [${missingCaption.join(', ')}]; no file for [${missingFile.join(', ')}]`);
  }
  const out = [];
  out.push('# HAAS render harness — screenshots');
  out.push('');
  out.push(`Generated by \`node tools/screens.js\` from \`${SCREENS_DIR}/captions.tsv\`; ${pngs.length} screenshots captured during the recorded browser walkthrough of the harness at http://localhost:8088/ (1280 px wide, Chrome). Filenames are prefixed with a 3-digit walkthrough sequence number. Do not edit by hand.`);
  out.push('');
  out.push('| # | Section | Screens |');
  out.push('|---|---|---|');
  const grouped = SECTIONS.map((s) => ({ ...s, files: pngs.filter((f) => { const n = Number(f.slice(0, 3)); return n >= s.from && n <= s.to; }) })).filter((s) => s.files.length);
  grouped.forEach((s, i) => out.push(`| ${i + 1} | [${s.title}](#${slug(s.title)}) | ${s.files.length} |`));
  out.push('');
  for (const s of grouped) {
    out.push(`## ${s.title}`);
    out.push('');
    out.push(s.blurb);
    out.push('');
    for (const f of s.files) {
      out.push(`### ${f.slice(4, -4)}`);
      out.push('');
      out.push(captions.get(f));
      out.push('');
      out.push(`![${f.slice(4, -4)}](screens/${f})`);
      out.push('');
    }
  }
  return out.join('\n');
}

function slug(title) {
  return title.toLowerCase().replace(/[^a-z0-9 -]/g, '').trim().replace(/\s+/g, '-');
}

if (require.main === module) {
  const md = build();
  if (process.argv.includes('--check')) {
    const current = fs.existsSync(OUTPUT_FILE) ? fs.readFileSync(OUTPUT_FILE, 'utf8') : '';
    if (current !== md) {
      console.error(`${OUTPUT_FILE} is stale; run node tools/screens.js`);
      process.exit(1);
    }
    console.log(`${OUTPUT_FILE} is current`);
  } else {
    fs.writeFileSync(OUTPUT_FILE, md);
    console.log(`wrote ${OUTPUT_FILE}`);
  }
}

module.exports = { build, readCaptions, SECTIONS };
